# Generated by Django 4.0.5 on 2022-06-16 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predmeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('kod', models.CharField(max_length=30)),
                ('program', models.TextField()),
                ('bodovi', models.IntegerField()),
                ('sem_redovni', models.IntegerField()),
                ('sem_izvanredni', models.IntegerField()),
                ('izborni', models.CharField(choices=[('da', 'DA'), ('ne', 'NE')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UpisniList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('predmet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.predmeti')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'ADMINISTRATOR'), ('prof', 'PROFESOR'), ('stud', 'STUDENT')], max_length=30)),
                ('status', models.CharField(choices=[('red', 'REDOVNI'), ('izvan', 'IZVANREDNI')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nositelj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nositelj', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('predmeti', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.predmeti')),
            ],
        ),
    ]
